# ****** Important note ******
# Remove unexpected backslashes from source csv file prior to running this script

import csv
import json
import sys
from collections import defaultdict

def tokenize(sentence, target_pos=None, condition=None):
    """Split sentence into word objects with lbr flags."""
    words = sentence.strip().split()
    target_idx = int(target_pos) - 1 if target_pos and int(target_pos) != 0 else None
    result = []
    for i, w in enumerate(words):
        if target_idx is not None:
            if i == target_idx:
                region = "critical"
            elif i == target_idx + 1:
                region = "spillover_1"
            elif i == target_idx + 2:
                region = "spillover_2"
            elif i == target_idx + 3:
                region = "spillover_3"
            elif i == target_idx - 3:
                region = "contrast"
            else:
                region = "0"
        else:
            region = "0"
        lbr_before = bool(condition and condition.startswith("NEW-") and target_idx is not None and i == target_idx - 2)
        lbr_after = bool(condition and condition.startswith("NEW-") and target_idx is not None and i == target_idx - 3)
        result.append({
            "form": w,
            "lbr_before": lbr_before,
            "lbr_after": lbr_after,
            "region": region
        })
    return result

def build_trial(row, trial_type):
    """Build a single trial object from a CSV row."""
    return {
        "condition": row["Condition"],
        "words": tokenize(row["Sentence"], row["TargetPos"], row["Condition"]),
        "question": row["Question"],
        "correct_answer": row["Correct"],
        "incorrect_answer": row["Incorrect"],
        "target_pos": row["TargetPos"],
        "adj1": row["Adj1"],
        "adj2": row["Adj2"],
        "type": trial_type,
        "trial_id": f"{trial_type}_{row['Item']}_{row['Condition']}"
    }

def convert(csv_path, output_path="stims.js"):
    fillers = []
    critical_by_item = defaultdict(list)

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            is_filler = ("PROVO" in row["Condition"] or "UNGRAMM" in row["Condition"]) or "PRACTICE" in row["Condition"]

            if is_filler:
                trial = build_trial(row, "filler")
                fillers.append(trial)
            else:
                trial = build_trial(row, "critical")
                critical_by_item[row["Item"]].append(trial)

    # Build grouped critical items structure
    critical_items = [
        {
            "item_id": f"critical_{item_id}",
            "conditions": conditions
        }
        for item_id, conditions in sorted(critical_by_item.items())
    ]

    js = "// Auto-generated by csv_to_stims.py — do not edit by hand\n\n"
    js += "var critical_items = " + json.dumps(critical_items, indent=2) + ";\n\n"
    js += "var fillers = " + json.dumps(fillers, indent=2) + ";\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Written to {output_path}")
    print(f"  {len(critical_by_item)} critical items ({sum(len(v) for v in critical_by_item.values())} rows)")
    print(f"  {len(fillers)} fillers")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python csv_to_stims.py data.csv [output.js]")
        sys.exit(1)

    csv_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "stims.js"
    convert(csv_path, output_path)